-- Conteo de datos

SELECT COUNT(*) AS PAISES FROM PAIS;
SELECT COUNT(*) AS REGIONES FROM REGION;
SELECT COUNT(*) AS DEPARTAMENTOS FROM DEPARTAMENTO;
SELECT COUNT(*) AS MUNICIPIOS FROM MUNICIPIO;
SELECT COUNT(*) AS RAZA FROM RAZA;
SELECT COUNT(*) AS GENERO FROM GENERO;
SELECT COUNT(*) AS ELECCIONES FROM ELECCION;


-- CONSULTA 1
-- Desplegar para cada elección el país y el partido político que obtuvo mayor porcentaje de votos
-- en su país. Debe desplegar el nombre de la elección, el año de la elección, el país, el nombre
-- del partido político y el porcentaje que obtuvo de votos en su país

select DO.NOMBREP AS NOMBRE_ELECCION, DO.Año, DO.Pais, CU.Partido , ROUND(DO.MAYOR / TR.votos *100, 2) AS PORCENTAJE from
(select PR.Nombre AS NOMBREP, PR.Año, PR.PAIS,  MAX(PR.votos) AS MAYOR from (
SELECT E.NOMBRE_ELECCION as Nombre, E.ANIO as Año, P.NOMBRE_PAIS as Pais, PA.NOMBRE_PARTIDO as Partido, SUM(E.ANALFAVETOS + E.ALFAVETOS) as votos 
FROM ELECCION E, MUNICIPIO M, DEPARTAMENTO D, REGION R, PAIS P, PARTIDO PA
WHERE E.MUNICIPIO_ID_MUNICIPIO = M.ID_MUNICIPIO
AND M.DEPARTAMENTO_ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
AND D.REGION_ID_REGION = R.ID_REGION
AND R.PAIS_ID_PAIS = P.ID_PAIS
AND E.PARTIDO_ID_PARTIDO = PA.ID_PARTIDO
GROUP BY E.NOMBRE_ELECCION, E.ANIO, P.NOMBRE_PAIS, PA.NOMBRE_PARTIDO
order by P.NOMBRE_PAIS
) PR group by PR.Nombre, PR.Año, PR.PAIS  ORDER BY PR.Pais) DO, 
(SELECT E.NOMBRE_ELECCION as Nombre, E.ANIO as Año, P.NOMBRE_PAIS as Pais, SUM(E.ANALFAVETOS + E.ALFAVETOS) as votos 
FROM ELECCION E, MUNICIPIO M, DEPARTAMENTO D, REGION R, PAIS P, PARTIDO PA
WHERE E.MUNICIPIO_ID_MUNICIPIO = M.ID_MUNICIPIO
AND M.DEPARTAMENTO_ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
AND D.REGION_ID_REGION = R.ID_REGION
AND R.PAIS_ID_PAIS = P.ID_PAIS
AND E.PARTIDO_ID_PARTIDO = PA.ID_PARTIDO
GROUP BY E.NOMBRE_ELECCION, E.ANIO, P.NOMBRE_PAIS
order by P.NOMBRE_PAIS) TR, (SELECT E.NOMBRE_ELECCION as Nombre, E.ANIO as Año, P.NOMBRE_PAIS as Pais, PA.NOMBRE_PARTIDO as Partido, SUM(E.ANALFAVETOS + E.ALFAVETOS) as votos 
FROM ELECCION E, MUNICIPIO M, DEPARTAMENTO D, REGION R, PAIS P, PARTIDO PA
WHERE E.MUNICIPIO_ID_MUNICIPIO = M.ID_MUNICIPIO
AND M.DEPARTAMENTO_ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
AND D.REGION_ID_REGION = R.ID_REGION
AND R.PAIS_ID_PAIS = P.ID_PAIS
AND E.PARTIDO_ID_PARTIDO = PA.ID_PARTIDO
GROUP BY E.NOMBRE_ELECCION, E.ANIO, P.NOMBRE_PAIS, PA.NOMBRE_PARTIDO
order by P.NOMBRE_PAIS) CU
WHERE TR.Nombre = DO.NOMBREP
AND DO.Año = TR.Año
AND DO.Pais = TR.Pais
AND DO.NOMBREP = CU.NOMBRE
AND DO.AÑO = CU.AÑO
AND DO.PAIS = CU.PAIS
AND DO.MAYOR = CU.VOTOS;

-- CONSULTA 2
-- Desplegar el total de votos y el porcentaje de votos emitidos por mujeres indígenas alfabetas.

SELECT PR.VOTOS AS TOTAL_VOTOS, ROUND(MU.VOTOS/PR.VOTOS*100,2) AS PORCENTAJE_MUJERES_INDIGENAS_ALFAVETAS FROM 
(SELECT SUM(E.ALFAVETOS + E.ANALFAVETOS) AS VOTOS  FROM ELECCION E) PR,
(SELECT SUM(E.ALFAVETOS) AS VOTOS  FROM ELECCION E, GENERO G, RAZA R
WHERE E.GENERO_ID_GENERO = G.ID_GENERO
AND E.RAZA_ID_RAZA = R.ID_RAZA
AND UPPER(G.NOMBRE_GENERO) = 'MUJERES'
AND UPPER(R.NOMBRE_RAZA) = 'INDIGENAS' ) MU;

-- CONSULTA 3
-- Desplegar total de votos y porcentaje de votos de mujeres por departamento y país. El ciento
-- por ciento es el total de votos de mujeres por país. (Tip: Todos los porcentajes por departamento
-- de un país deben sumar el 100%)

SELECT TOT.VOTOS, TOT.NOMBRE_PAIS AS PAIS, PAR.NOMBRE_DEPARTAMENTO AS DEPARTAMENTO, ROUND(PAR.VOTOS / TOT.VOTOS * 100,2) as Porcentaje FROM (SELECT SUM(E.ALFAVETOS + E.ANALFAVETOS) AS VOTOS, PA.NOMBRE_PAIS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, GENERO GE
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
AND E.GENERO_ID_GENERO = GE.ID_GENERO
AND UPPER(GE.NOMBRE_GENERO) = 'MUJERES'
GROUP BY PA.NOMBRE_PAIS) TOT, (SELECT SUM(E.ALFAVETOS + E.ANALFAVETOS) AS VOTOS, PA.NOMBRE_PAIS, DE.NOMBRE_DEPARTAMENTO FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, GENERO GE
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
AND E.GENERO_ID_GENERO = GE.ID_GENERO
AND UPPER(GE.NOMBRE_GENERO) = 'MUJERES'
GROUP BY PA.NOMBRE_PAIS, DE.NOMBRE_DEPARTAMENTO) PAR
WHERE TOT.NOMBRE_PAIS = PAR.NOMBRE_PAIS
ORDER BY TOT.NOMBRE_PAIS,ROUND(PAR.VOTOS / TOT.VOTOS * 100,2);


-- CONSULRA 4
-- Desplegar el nombre del país, el porcentaje de votos de ese país en el que han votado mayor
-- porcentaje de analfabetas. (tip: solo desplegar un nombre de país, el de mayor porcentaje).

SELECT * FROM (
SELECT TOT.NOMBRE_PAIS AS PAIS, ROUND( AL.VOTOS / TOT.VOTOS * 100 ,2) AS PROSENTAJE_ANALFAVETOS FROM (SELECT SUM(E.ALFAVETOS + E.ANALFAVETOS) AS VOTOS, PA.NOMBRE_PAIS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, GENERO GE
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
GROUP BY PA.NOMBRE_PAIS
ORDER BY PA.NOMBRE_PAIS) TOT, (SELECT SUM(E.ANALFAVETOS) AS VOTOS, PA.NOMBRE_PAIS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, GENERO GE
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
GROUP BY PA.NOMBRE_PAIS
ORDER BY PA.NOMBRE_PAIS) AL
WHERE TOT.NOMBRE_PAIS = AL.NOMBRE_PAIS
ORDER BY ROUND( AL.VOTOS / TOT.VOTOS * 100 ,2) DESC)
WHERE ROWNUM = 1;


-- CONSULTA 5
-- Desplegar el nombre del país, nombre del partido político y número de alcaldías de los partidos
-- políticos que ganaron más alcaldías por país.


SELECT TOTAL.PAIS, PART.PARTIDO, TOTAL.CANTIDAD FROM (SELECT TOT.PAIS AS PAIS, MAX(CANTIDAD) AS CANTIDAD FROM (
SELECT RA.PAIS, RA.PARTIDO, COUNT(RA.MUNA) AS CANTIDAD FROM
(select UNO.PAIS AS PAIS, UNO.PARTIDO AS PARTIDO, UNO.IDMUN AS MUNA, DOS.VOTOS from (SELECT PA.NOMBRE_PAIS AS PAIS, PAR.NOMBRE_PARTIDO AS PARTIDO, MU.ID_MUNICIPIO AS IDMUN ,SUM(E.ANALFAVETOS + E.ALFAVETOS)  AS VOTOS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, PARTIDO PAR
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
AND E.PARTIDO_ID_PARTIDO = PAR.ID_PARTIDO
GROUP BY PA.NOMBRE_PAIS, PAR.NOMBRE_PARTIDO, MU.ID_MUNICIPIO
ORDER BY PA.NOMBRE_PAIS,  MU.ID_MUNICIPIO) UNO, 
(SELECT UN.PAIS AS PAIS, UN.MUN AS IDMUN , MAX(UN.VOTOS) AS VOTOS FROM
(SELECT PA.NOMBRE_PAIS AS PAIS, PAR.NOMBRE_PARTIDO AS PARTIDO, MU.ID_MUNICIPIO AS MUN, MU.NOMBRE_MUNICIPIO ,SUM(E.ANALFAVETOS + E.ALFAVETOS)  AS VOTOS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, PARTIDO PAR
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
AND E.PARTIDO_ID_PARTIDO = PAR.ID_PARTIDO
GROUP BY PA.NOMBRE_PAIS, PAR.NOMBRE_PARTIDO, MU.ID_MUNICIPIO, MU.NOMBRE_MUNICIPIO
ORDER BY PA.NOMBRE_PAIS,  MU.ID_MUNICIPIO) UN 
group by UN.PAIS,  UN.MUN order by un.mun) DOS
WHERE UNO.PAIS = DOS.PAIS
AND UNO.IDMUN = DOS.IDMUN
AND UNO.VOTOS = DOS.VOTOS
ORDER BY UNO.IDMUN) RA group by RA.PAIS, RA.PARTIDO) TOT group by TOT.PAIS) TOTAL, 
(SELECT RA.PAIS, RA.PARTIDO, COUNT(RA.MUNA) AS CANTIDAD FROM
(select UNO.PAIS AS PAIS, UNO.PARTIDO AS PARTIDO, UNO.IDMUN AS MUNA, DOS.VOTOS from (SELECT PA.NOMBRE_PAIS AS PAIS, PAR.NOMBRE_PARTIDO AS PARTIDO, MU.ID_MUNICIPIO AS IDMUN ,SUM(E.ANALFAVETOS + E.ALFAVETOS)  AS VOTOS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, PARTIDO PAR
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
AND E.PARTIDO_ID_PARTIDO = PAR.ID_PARTIDO
GROUP BY PA.NOMBRE_PAIS, PAR.NOMBRE_PARTIDO, MU.ID_MUNICIPIO
ORDER BY PA.NOMBRE_PAIS,  MU.ID_MUNICIPIO) UNO, 
(SELECT UN.PAIS AS PAIS, UN.MUN AS IDMUN , MAX(UN.VOTOS) AS VOTOS FROM
(SELECT PA.NOMBRE_PAIS AS PAIS, PAR.NOMBRE_PARTIDO AS PARTIDO, MU.ID_MUNICIPIO AS MUN, MU.NOMBRE_MUNICIPIO ,SUM(E.ANALFAVETOS + E.ALFAVETOS)  AS VOTOS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, PARTIDO PAR
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
AND E.PARTIDO_ID_PARTIDO = PAR.ID_PARTIDO
GROUP BY PA.NOMBRE_PAIS, PAR.NOMBRE_PARTIDO, MU.ID_MUNICIPIO, MU.NOMBRE_MUNICIPIO
ORDER BY PA.NOMBRE_PAIS,  MU.ID_MUNICIPIO) UN 
group by UN.PAIS,  UN.MUN order by un.mun) DOS
WHERE UNO.PAIS = DOS.PAIS
AND UNO.IDMUN = DOS.IDMUN
AND UNO.VOTOS = DOS.VOTOS
ORDER BY UNO.IDMUN) RA group by RA.PAIS, RA.PARTIDO) PART
WHERE TOTAL.PAIS = PART.PAIS
AND TOTAL.CANTIDAD = PART.CANTIDAD
;

-- consulta 6
-- Desplegar todas las regiones por país en las que predomina la raza indígena. Es decir, hay
-- más votos que las otras razas.

SELECT C61.PAIS, C61.REGION FROM (SELECT PA.NOMBRE_PAIS AS  PAIS, RE.NOMBRE_REGION AS REGION, RA.NOMBRE_RAZA AS RAZA, SUM(E.ALFAVETOS + E.ANALFAVETOS) AS VOTOS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, RAZA RA
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
AND E.RAZA_ID_RAZA = RA.ID_RAZA
GROUP BY PA.NOMBRE_PAIS, RE.NOMBRE_REGION, RA.NOMBRE_RAZA
ORDER BY PA.NOMBRE_PAIS, RE.NOMBRE_REGION, RA.NOMBRE_RAZA) C61, (SELECT PAIS AS PAIS, REGION AS REGION, MAX(VOTOS) AS VOTOS FROM (SELECT PAIS AS PAIS, REGION AS REGION, MAX(VOTOS) AS VOTOS FROM ( SELECT PA.NOMBRE_PAIS AS  PAIS, RE.NOMBRE_REGION AS REGION, RA.NOMBRE_RAZA AS RAZA, SUM(E.ALFAVETOS + E.ANALFAVETOS) AS VOTOS 
FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, RAZA RA
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
AND E.RAZA_ID_RAZA = RA.ID_RAZA
GROUP BY PA.NOMBRE_PAIS, RE.NOMBRE_REGION, RA.NOMBRE_RAZA
ORDER BY PA.NOMBRE_PAIS, RE.NOMBRE_REGION, RA.NOMBRE_RAZA) 
group by PAIS, REGION
ORDER BY PAIS, REGION) CONS6 
group by PAIS, REGION
ORDER BY PAIS, REGION) C62
WHERE C61.PAIS = C62.PAIS
AND C61.REGION = C62.REGION
AND C61.VOTOS = C62.VOTOS
AND C61.RAZA = 'INDIGENAS' ;

-- CONSULTA 7
-- Desplegar el porcentaje de mujeres universitarias y hombres universitarios que votaron por
-- departamento, donde las mujeres universitarias que votaron fueron más que los hombres
-- universitarios que votaron.

SELECT HOM.DEPID AS ID_DEP, MUJ.DEP AS DEPARTAMENTO, ROUND(MUJ.VOTOS / (MUJ.VOTOS + HOM.VOTOS) *100, 2) AS MUJERES, ROUND(HOM.VOTOS / (MUJ.VOTOS + HOM.VOTOS) *100,2) AS HOMBRES FROM (SELECT DE.ID_DEPARTAMENTO AS DEPID, DE.NOMBRE_DEPARTAMENTO AS DEP, GE.NOMBRE_GENERO AS GEN, SUM(E.UNIVERSITARIO) AS VOTOS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, GENERO GE
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
AND E.GENERO_ID_GENERO = GE.ID_GENERO 
AND UPPER(GE.NOMBRE_GENERO) = 'HOMBRES'
group by DE.ID_DEPARTAMENTO, DE.NOMBRE_DEPARTAMENTO, GE.NOMBRE_GENERO
ORDER BY DE.ID_DEPARTAMENTO, DE.NOMBRE_DEPARTAMENTO, GE.NOMBRE_GENERO) HOM, 
(SELECT DE.ID_DEPARTAMENTO AS DEPID, DE.NOMBRE_DEPARTAMENTO AS DEP, GE.NOMBRE_GENERO AS GEN, SUM(E.UNIVERSITARIO) AS VOTOS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, GENERO GE
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
AND E.GENERO_ID_GENERO = GE.ID_GENERO 
AND UPPER(GE.NOMBRE_GENERO) = 'MUJERES'
group by DE.ID_DEPARTAMENTO, DE.NOMBRE_DEPARTAMENTO, GE.NOMBRE_GENERO
ORDER BY DE.ID_DEPARTAMENTO, DE.NOMBRE_DEPARTAMENTO, GE.NOMBRE_GENERO) MUJ
WHERE HOM.DEPID = MUJ.DEPID
AND HOM.DEP = MUJ.DEP
AND MUJ.VOTOS > HOM.VOTOS
;

-- CONSULTA 8
-- Desplegar la lista de departamentos de Guatemala y número de votos obtenidos, para los
-- departamentos que obtuvieron más votos que el departamento de Guatemala.

SELECT DEPA.DEP, DEPA.VOTOS AS DEPARTAMENTO FROM (SELECT DE.ID_DEPARTAMENTO AS DEPID, DE.NOMBRE_DEPARTAMENTO AS DEP, SUM(E.ALFAVETOS + E.ANALFAVETOS) AS VOTOS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS 
AND UPPER(PA.NOMBRE_PAIS) = 'GUATEMALA'
group by DE.ID_DEPARTAMENTO, DE.NOMBRE_DEPARTAMENTO) DEPA, (SELECT DE.ID_DEPARTAMENTO AS DEPID, DE.NOMBRE_DEPARTAMENTO AS DEP, SUM(E.ALFAVETOS + E.ANALFAVETOS) AS VOTOS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS 
AND UPPER(PA.NOMBRE_PAIS) = 'GUATEMALA'
AND UPPER(DE.NOMBRE_DEPARTAMENTO) = 'GUATEMALA'
group by DE.ID_DEPARTAMENTO, DE.NOMBRE_DEPARTAMENTO) GUATE
WHERE DEPA.VOTOS > GUATE.VOTOS
;

-- CONSULTA 9 
-- Desplegar el nombre del país, la región y el promedio de votos por departamento. Por ejemplo:
-- Si la región tiene tres departamentos, se debe sumar todos los votos de la región y dividirlo dentro
-- de tres (número de departamentos de la región).


SELECT TOTAL.PAIS AS PAIS, TOTAL.REGI AS REGION, ROUND(CONT.VOTOS / CONT.CANT,2)  AS PROMEDIO
FROM (SELECT PA.NOMBRE_PAIS AS PAIS, RE.NOMBRE_REGION  AS REGI, DE.ID_DEPARTAMENTO AS DEPID FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS 
group by PA.NOMBRE_PAIS,  RE.NOMBRE_REGION, DE.ID_DEPARTAMENTO 
ORDER BY PA.NOMBRE_PAIS,  RE.NOMBRE_REGION, DE.ID_DEPARTAMENTO) TOTAL, 
( SELECT DEPA.PAIS AS PAIS, DEPA.REG AS REG, COUNT(DEPA.DEPID) AS CANT, SUM(DEPA.VOTOS) AS VOTOS  FROM (SELECT PA.NOMBRE_PAIS AS PAIS, RE.NOMBRE_REGION  AS REG, DE.ID_DEPARTAMENTO AS DEPID, SUM(E.ALFAVETOS + E.ALFAVETOS) AS VOTOS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS 
group by PA.NOMBRE_PAIS,  RE.NOMBRE_REGION, DE.ID_DEPARTAMENTO 
ORDER BY PA.NOMBRE_PAIS,  RE.NOMBRE_REGION, DE.ID_DEPARTAMENTO ) DEPA 
group by DEPA.PAIS, DEPA.REG 
ORDER BY DEPA.PAIS, DEPA.REG  ) CONT 
WHERE TOTAL.PAIS = CONT.PAIS
AND TOTAL.REGI = CONT.REG
GROUP BY TOTAL.PAIS, TOTAL.REGI, ROUND(CONT.VOTOS / CONT.CANT,2)
ORDER BY TOTAL.PAIS, TOTAL.REGI
;

-- CONULTA 10
-- Desplegar el total de votos de los municipios agrupados por su letra inicial. Es decir, agrupar
-- todos los municipios con letra A y calcular su número de votos, lo mismo para los de letra inicial
-- B, y así sucesivamente hasta la Z.


SELECT  UPPER(SUBSTR(MU.NOMBRE_MUNICIPIO,1,1)) AS INICIAL, SUM(E.ALFAVETOS + E.ANALFAVETOS) AS VOTOS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS group by SUBSTR(MU.NOMBRE_MUNICIPIO,1,1)
ORDER BY UPPER(SUBSTR(MU.NOMBRE_MUNICIPIO,1,1))
;


-- CONSULTA 11
-- Desplegar el nombre del municipio y el nombre de los dos partidos políticos con más votos
-- en el municipio, ordenados por país.


SELECT DOS.PAIS, DOS.MUNICIPIO, DOS.PARTIDO FROM(
SELECT UNO.PAIS AS PAIS, UNO.MUNICIPIO AS MUNICIPIO, UNO.PARTIDO AS PARTIDO, ROW_NUMBER() OVER (PARTITION BY UNO.PAIS,UNO.MUNICIPIO ORDER BY UNO.VOTOS desc) AS VOTOS_RANK, UNO.VOTOS
FROM (
SELECT PA.NOMBRE_PAIS AS PAIS, MU.NOMBRE_MUNICIPIO AS MUNICIPIO, PAR.NOMBRE_PARTIDO AS PARTIDO, SUM(E.ANALFAVETOS + E.ALFAVETOS) AS VOTOS 
FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, PARTIDO PAR
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
AND E.PARTIDO_ID_PARTIDO = PAR.ID_PARTIDO 
group by PA.NOMBRE_PAIS, MU.NOMBRE_MUNICIPIO, PAR.NOMBRE_PARTIDO
) UNO
ORDER BY UNO.PAIS, UNO.MUNICIPIO, VOTOS_RANK
) DOS
WHERE DOS.VOTOS_RANK <= 2
ORDER BY DOS.PAIS, DOS.MUNICIPIO, DOS.VOTOS_RANK;


-- CONSULTA 12
-- Desplegar el total de votos de cada nivel de escolaridad (primario, medio, universitario) por
-- país, sin importar raza o sexo.

SELECT PA.NOMBRE_PAIS AS PAIS, SUM(E.PRIMARIA) AS PRIMARIA, SUM(E.MEDIO) AS MEDIO, SUM(E.UNIVERSITARIO) AS UNIVERSITARIO FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
GROUP BY PA.NOMBRE_PAIS
ORDER BY PA.NOMBRE_PAIS
;

-- CONSULTA 13
-- Desplegar el nombre del país y el porcentaje de votos por raza.

SELECT UNO.PAIS, UNO.RAZA, ROUND(UNO.VOTOS/DOS.VOTOS_TOTAL *100,2) AS PORCENTAJE FROM
(SELECT PA.NOMBRE_PAIS AS PAIS, RA.NOMBRE_RAZA AS RAZA, SUM(E.ANALFAVETOS + E.ALFAVETOS) AS VOTOS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, RAZA RA
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
AND E.RAZA_ID_RAZA = RA.ID_RAZA 
group by PA.NOMBRE_PAIS, RA.NOMBRE_RAZA) UNO,
(SELECT PA.NOMBRE_PAIS AS PAIS, SUM(E.ANALFAVETOS + E.ALFAVETOS) AS VOTOS_TOTAL FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
group by PA.NOMBRE_PAIS) DOS
WHERE UNO.PAIS = DOS.PAIS
ORDER BY UNO.PAIS, UNO.RAZA
;

-- CONUSLTA 14
-- Desplegar el nombre del país en el cual las elecciones han sido más peleadas. Para
-- determinar esto se debe calcular la diferencia de porcentajes de votos entre el partido que obtuvo
-- más votos y el partido que obtuvo menos votos.

SELECT PAIS FROM (
SELECT TRES.PAIS AS PAIS, MAX(TRES.PORCENTAJE) - MIN(TRES.PORCENTAJE) AS DIFERENCIA  FROM (
SELECT UNO.PAIS AS PAIS, UNO.PARTIDO, UNO.VOTOS / DOS.VOTOS_TOTAL * 100 PORCENTAJE FROM 
(SELECT PA.NOMBRE_PAIS AS PAIS, PAR.NOMBRE_PARTIDO AS PARTIDO, SUM(E.ANALFAVETOS + E.ALFAVETOS) AS VOTOS FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA, PARTIDO PAR
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
AND E.PARTIDO_ID_PARTIDO = PAR.ID_PARTIDO
group by PA.NOMBRE_PAIS, PAR.NOMBRE_PARTIDO) UNO, 
(SELECT PA.NOMBRE_PAIS AS PAIS, SUM(E.ANALFAVETOS + E.ALFAVETOS) AS VOTOS_TOTAL FROM ELECCION E, MUNICIPIO MU, DEPARTAMENTO DE, REGION RE, PAIS PA
WHERE E.MUNICIPIO_ID_MUNICIPIO = MU.ID_MUNICIPIO
AND MU.DEPARTAMENTO_ID_DEPARTAMENTO = DE.ID_DEPARTAMENTO
AND DE.REGION_ID_REGION = RE.ID_REGION
AND RE.PAIS_ID_PAIS = PA.ID_PAIS
group by PA.NOMBRE_PAIS) DOS
WHERE UNO.PAIS = DOS.PAIS
ORDER BY UNO.PAIS
) TRES group by TRES.PAIS
ORDER BY DIFERENCIA)
WHERE ROWNUM = 1
;
