

INSERT INTO PAIS (NOMBRE_PAIS)
SELECT DISTINCT T.PAIS FROM TEMPORAL T
ORDER BY T.PAIS;
COMMIT;

INSERT INTO REGION (NOMBRE_REGION, PAIS_ID_PAIS)
SELECT DISTINCT T.region, P.ID_PAIS from TEMPORAL T, PAIS P
WHERE T.PAIS = P.NOMBRE_PAIS
ORDER BY T.region;
COMMIT;

INSERT INTO DEPARTAMENTO (NOMBRE_DEPARTAMENTO, REGION_ID_REGION)
SELECT DISTINCT T.DEPTO, R.ID_REGION FROM TEMPORAL T, REGION R, PAIS P
WHERE T.REGION = R.NOMBRE_REGION
AND T.PAIS = P.NOMBRE_PAIS
AND R.PAIS_ID_PAIS = P.ID_PAIS
ORDER BY T.DEPTO;
COMMIT;

INSERT INTO MUNICIPIO (NOMBRE_MUNICIPIO,DEPARTAMENTO_ID_DEPARTAMENTO)
SELECT DISTINCT T.MUN, D.ID_DEPARTAMENTO FROM TEMPORAL T, DEPARTAMENTO D, REGION R, PAIS P
WHERE T.DEPTO = D.NOMBRE_DEPARTAMENTO
AND T.REGION = R.NOMBRE_REGION
AND D.REGION_ID_REGION = R.ID_REGION
AND T.PAIS = P.NOMBRE_PAIS
AND R.PAIS_ID_PAIS = P.ID_PAIS
ORDER BY T.MUN;
COMMIT;

INSERT INTO PARTIDO (INICIALES_PARTIDO,NOMBRE_PARTIDO)
SELECT DISTINCT T.PAR, T.NOMPAR FROM TEMPORAL T
ORDER BY T.PAR;
COMMIT;

INSERT INTO RAZA (NOMBRE_RAZA)
SELECT DISTINCT T.RAZA FROM TEMPORAL T;
COMMIT;

INSERT INTO GENERO (NOMBRE_GENERO)
SELECT DISTINCT T.SEXO FROM TEMPORAL T;
COMMIT;


INSERT INTO ELECCION (NOMBRE_ELECCION, ANIO, ANALFAVETOS, ALFAVETOS, PRIMARIA, MEDIO, 
UNIVERSITARIO, MUNICIPIO_ID_MUNICIPIO, PARTIDO_ID_PARTIDO, GENERO_ID_GENERO, RAZA_ID_RAZA)      
SELECT T.NOM_ELEC, T.ANIO, T.ANALFAVETOS, T.ALFAVETOS, T.PRIMARIA, T.MEDIO, T.UNIVESITARIOS, M.ID_MUNICIPIO, PA.ID_PARTIDO, G.ID_GENERO, RA.ID_RAZA
    FROM TEMPORAL T, MUNICIPIO M, DEPARTAMENTO D, REGION R, PAIS P, PARTIDO PA, GENERO G, RAZA RA       
        WHERE T.MUN = M.NOMBRE_MUNICIPIO
        AND T.PAIS = P.NOMBRE_PAIS
        AND T.REGION = R.NOMBRE_REGION
        AND T.DEPTO = D.NOMBRE_DEPARTAMENTO
        AND T.PAR = PA.INICIALES_PARTIDO
        AND T.NOMPAR = PA.NOMBRE_PARTIDO
        AND T.SEXO = G.NOMBRE_GENERO
        AND T.RAZA = RA.NOMBRE_RAZA
        AND M.DEPARTAMENTO_ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
        AND D.REGION_ID_REGION = R.ID_REGION
        AND R.PAIS_ID_PAIS = P.ID_PAIS ORDER BY M.ID_MUNICIPIO;
COMMIT;


DROP TABLE temporal CASCADE CONSTRAINTS;

QUIT;